apiVersion: operator.openshift.io/v1alpha1
kind: MustGather
metadata:
  name: example-mustgather-staging
spec:
  uploadTarget:
    type: SFTP
    sftp:
      caseID: '02527285'
      caseManagementAccountSecretRef:
        name: case-management-creds
      host: sftp.access.stage.redhat.com
  serviceAccountRef:
    name: must-gather-admin
